const wordList = [
    { word: "amigo", hint: "Una persona con la que tienes una relación de afecto y confianza." },
    { word: "avión", hint: "Medio de transporte aéreo." },
    { word: "barco", hint: "Medio de transporte marítimo." },
    { word: "bosque", hint: "Área con muchos árboles." },
    { word: "casa", hint: "Lugar donde vive la gente." },
    { word: "cocina", hint: "Lugar donde se preparan alimentos." },
    { word: "diamante", hint: "Piedra preciosa muy dura y brillante." },
    { word: "destino", hint: "Lugar al que se dirige alguien o algo." },
    { word: "elefante", hint: "El mamífero terrestre más grande." },
    { word: "estrella", hint: "Cuerpo celeste que brilla en el cielo nocturno." },
    { word: "familia", hint: "Conjunto de personas emparentadas entre sí." },
    { word: "fiesta", hint: "Reunión de personas para celebrar algo." },
    { word: "guitarra", hint: "Instrumento musical de cuerdas." },
    { word: "girasol", hint: "Flor que sigue al sol." },
    { word: "helado", hint: "Postre frío hecho de crema o leche." },
    { word: "héroe", hint: "Persona admirada por sus hazañas y virtudes." },
    { word: "invierno", hint: "Estación más fría del año." },
    { word: "iglesia", hint: "Edificio destinado al culto religioso." },
    { word: "jardín", hint: "Área con plantas y flores." },
    { word: "juguete", hint: "Objeto con el que juegan los niños." },
    { word: "karate", hint: "Arte marcial de origen japonés." },
    { word: "kimono", hint: "Vestimenta tradicional japonesa." },
    { word: "libro", hint: "Conjunto de hojas escritas o impresas." },
    { word: "luna", hint: "Satélite natural de la Tierra." },
    { word: "montaña", hint: "Gran elevación natural del terreno." },
    { word: "maestro", hint: "Persona que enseña en una escuela." },
    { word: "noche", hint: "Parte del día cuando no hay luz solar." },
    { word: "noticia", hint: "Información nueva sobre un evento reciente." },
    { word: "ñame", hint: "Tubérculo comestible." },
    { word: "ñoño", hint: "Persona sosa y aburrida." },
    { word: "océano", hint: "Gran extensión de agua salada que cubre la mayor parte de la superficie terrestre." },
    { word: "orquesta", hint: "Grupo de músicos que tocan instrumentos juntos." },
    { word: "princesa", hint: "Hija de un rey o reina." },
    { word: "planeta", hint: "Cuerpo celeste que orbita una estrella." },
    { word: "queso", hint: "Alimento sólido hecho de leche cuajada." },
    { word: "química", hint: "Ciencia que estudia la composición y propiedades de la materia." },
    { word: "ratón", hint: "Pequeño roedor." },
    { word: "rosa", hint: "Flor de color rojo, blanco, amarillo, etc." },
    { word: "sol", hint: "Estrella en el centro del sistema solar." },
    { word: "sueño", hint: "Deseo o aspiración." },
    { word: "teatro", hint: "Lugar donde se representan obras dramáticas." },
    { word: "tesoro", hint: "Conjunto de cosas de mucho valor." },
    { word: "unicornio", hint: "Animal mitológico con un cuerno en la frente." },
    { word: "universo", hint: "Conjunto de todo lo que existe." },
    { word: "volcán", hint: "Abertura en la corteza terrestre por donde salen materiales incandescentes." },
    { word: "viaje", hint: "Desplazamiento de un lugar a otro." },
    { word: "whisky", hint: "Bebida alcohólica destilada." },
    { word: "wafle", hint: "Postre hecho con masa cocida en una plancha especial." },
    { word: "xilófono", hint: "Instrumento musical de percusión." },
    { word: "xenón", hint: "Elemento químico gaseoso." },
    { word: "yate", hint: "Embarcación de recreo." },
    { word: "yegua", hint: "Hembra del caballo." },
    { word: "zapato", hint: "Calzado para el pie." },
    { word: "zanahoria", hint: "Raíz comestible de color naranja." },
    { word: "pingüino", hint: "Ave marina no voladora"}
];